### ISSUE TITLE
怎么用啊

### ISSUE THREAD

**Issue by xy0893** [CaptainMorch/certnet_network_list#1]
py-3 spider.py
py -3 spider.py output.csv
py -3 spider.py 哈佛大学 output.csv
都试过了啊， 脚本没反应

**Comment by CaptainMorch** [comment]
> py-3 spider.py
> py -3 spider.py output.csv
> py -3 spider.py 哈佛大学 output.csv
> 都试过了啊， 脚本没反应

你要做什么呢

**Comment by xy0893** [comment]
> > py-3 蜘蛛.py 
> > py -3 spider.py output.csv 
> > py -3 spider.py 哈佛大学 output.csv 
> > 都试过了啊， 脚本没反应
> 
> 你要做什么呢

大佬 我想运行脚本抓取一些美国的IP段， 你能告诉我正确启动脚本的格式吗？

**Comment by CaptainMorch** [comment]
> 大佬 我想运行脚本抓取一些美国的IP段， 你能告诉我正确启动脚本的格式吗？

1. 这是中国教育网的，美国的请自行搜索来爬；
2. 这里的py脚本只供 Github Action 每月自动抓取更新内容，和搜索内容没有任何关系。想临时搜索，浏览器里直接点开 output.csv 然后 Ctrl+F；想自动搜索，就使用 grep 一类或者自己写脚本读取遍历筛选
